<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function eds_help($route_name, RouteMatchInterface $route_match)
{
    switch ($route_name) {
        case 'help.page.eds':
            return t('
        <h2>EBSCO EDS integration for Drupal.</h2>
        <p>Most bugs have been ironed out, holes covered, features added. But this module is a work in progress. Please report bugs and suggestions, ok?</p>
      ');
    }
}

/**
 * Implements hook_theme().
 */
function eds_theme($existing, $type, $theme, $path)
{
    return [
        'eds' => [
            'variables' => [
                'id' => NULL,
                'header' => NULL,
                'p_link' => NULL,
                'image_info' => NULL,
                'items' => NULL,
                'custom_links' => NULL,
                'view' => NULL
            ],
        ],
    ];
}

/**
 * Implements hook_theme_suggestions().
 */
function eds_theme_suggestions_eds(array $variables)
{
    $view = $variables['view'];
    $suggestions = [];
    $suggestions[] = 'eds__view__' . $view->id();
    $suggestions[] = 'eds__view__' . $view->id() . '__' . $view->current_display;
    return $suggestions;
}

/**
 * Implements hook_preprocess_views_view().
 */
function eds_preprocess_views_view(array &$variables)
{
    // This works only if the exposed form in block is set to "No"
    $view = $variables['view'];

    if (!empty($view->exposed_data['facets'])) {
        $options = [];
        $options['Any']['any'] = '- Any -';

        $facet_id = 0;
        foreach ($view->exposed_data['facets'] as $facet) {
            $filter_id = $facet['Id'];
            $group = $facet['Label'];
            foreach ($facet['AvailableFacetValues'] as $value) {
                $facet_value = $value['Value'];
                $options[$group][$facet_id++ . "," . $filter_id . ":" . $facet_value] = $facet_value . " (" . $value["Count"] . ")";
            }
        }
        $variables['exposed']['eds_facets']['#options'] = $options;
    }
}
